In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [2]:
# columns names
header_list = ["age", "class of worker", "detailed industry recode",
               "detailed occupation recode", "education", "wage per hour",
              "enroll in edu inst last wk", "marital stat","major industry code",
              "major occupation code", "race", "hispanic origin",
              "sex", "member of a labor union", "reason for unemployment",
              "full or part time employment stat", "capital gains", "capital losses",
               "dividends from stocks", "tax filer stat", "region of previous residence",
               "state of previous residence", "detailed household and family stat",
               "detailed household summary in household",
               "instance weight", "migration code-change in msa", "migration code-change in reg",
               "migration code-move within reg", "live in this house 1 year ago", "migration prev res in sunbelt",
               "num persons worked for employer", "family members under 18", "country of birth father",
               "country of birth mother", "country of birth self", "citizenship",
               "own business or self employed", "fill inc questionnaire for veteran's admin", "veterans benefits",
               "weeks worked in year", "year", "income"
              ]

data = pd.read_csv("census-income.data", names=header_list)
num_features = [i for i in data.columns if data[i].dtypes != 'object'] # numerical
cat_features = [i for i in data.columns if i not in num_features] # categorical

In [3]:
data[num_features].head()

,age,detailed industry recode,detailed occupation recode,wage per hour,capital gains,capital losses,dividends from stocks,instance weight,num persons worked for employer,own business or self employed,veterans benefits,weeks worked in year,year
0,73,0,0,0,0,0,0,1700.09,0,0,2,0,95
1,58,4,34,0,0,0,0,1053.55,1,0,2,52,94
2,18,0,0,0,0,0,0,991.95,0,0,2,0,95
3,9,0,0,0,0,0,0,1758.14,0,0,0,0,94
4,10,0,0,0,0,0,0,1069.16,0,0,0,0,94

In [4]:
mapping = {' - 50000.': 1, ' 50000+.': 0}
data.income = [mapping[item] for item in data.income]

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data[num_features], data.income, test_size=0.2) # 80% - 20%

In [6]:
#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=9)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [7]:
from sklearn import metrics
from sklearn.metrics import classification_report

print("#### KNeighbors [k=5] ####")
print(classification_report(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

#### KNeighbors [k=5] ####
              precision    recall  f1-score   support

           0       0.63      0.25      0.36      2506
           1       0.95      0.99      0.97     37399

    accuracy                           0.94     39905
   macro avg       0.79      0.62      0.67     39905
weighted avg       0.93      0.94      0.93     39905

Accuracy: 0.9437915048239569